### ISSUE TITLE
Dependency on fastparse 1.0.0

### ISSUE THREAD

**Issue by kalanzai** [alonsodomin/cron4s#194]
My team and I would very much like to use your library in conjunction with [fs2-cron](https://github.com/fthomas/fs2-cron) help us with some of our issues. However, there seems to be a dependency on [fastparse](https://github.com/lihaoyi/fastparse) 1.0.0 in your library which clashes with the dependency we work with, 2.1.3. 

I don't fully understand your setup, but as best as I could determine the dependency is rooted in `docs.cron4s`. If that is correct then a possible solution could be to simply not bundle the `docs.cron4s` with the library itself?

**Comment by alonsodomin** [comment]
Hi @kalanzai, don't know from where are you taking that the FastParse dependency is coming from the docs but was part of the `core` module and it has already been removed in the latest milestone release (`0.6.0-M2`) which is available in Maven Central.

Notice that, even though that is a milestone release, the library is as stable as in the previous version, the milestone tag is due to some base dependencies (i.e. `cats`) not being final yet.

**Comment by kalanzai** [comment]
@alonsodomin Great! Thanks for your reply. As I said I don't fully understand your setup.

**Comment by alonsodomin** [comment]
no worries @kalanzai, if you find any problems with the milestone release don't hesitate on posting a new issue in here

**Comment by kalanzai** [comment]
I've updated my dependency of [fs2-cron](https://github.com/fthomas/fs2-cron) to [v0.2.1](https://github.com/fthomas/fs2-cron/releases/tag/v0.2.1) which uses your milestone release (`0.6.0-M2`). My fastparse dependency is still resolved to `2.1.3`. When I build there's a macro `cron` that fails because it cannot find the class `fastparse.core.Parser` which (as far as I can tell) was removed in `fastparse 2.0.4`.

**Comment by alonsodomin** [comment]
Sounds weird to me, do you have a link to that build (or one that reproduces the error)?

There is no fastparse of any shape or form on 0.6.0-M2 so I have no idea how you can see any classpath issue.

**Comment by alonsodomin** [comment]
You can see in this following link that `cron4s` 0.6.0-M2 doesn't have any dependency on FastParse, so I have no idea where it is coming from in your case:

https://search.maven.org/artifact/com.github.alonsodomin.cron4s/cron4s-core_2.12/0.6.0-M2/jar

**Comment by kalanzai** [comment]
Sorry to have wasted your time. It was simply a matter of me not having cleaned up the old binaries from the previous version. I can see that the `cron` macro is no longer a part of the package.

**Comment by alonsodomin** [comment]
No worries @kalanzai, at first I thought I had messed up something with the release.

Regarding the `cron` macro, it used to exist to provide handy compile-time cron expressions but decided to get rid of it due to some issues when compiling to Scala `2.13`. I may still try to get it back but it didn't have any influence on the FastParse issue either.
