### ISSUE TITLE
Wrong DateTime with "1 1 1 31 * ?" 

### ISSUE THREAD

**Issue by graingert** [alonsodomin/cron4s#73]
```scala
scala> val oldDate = new DateTime("2016-09-04T00:00:00.000Z", DateTimeZone.UTC)
oldDate: org.joda.time.DateTime = 2016-09-04T00:00:00.000Z

scala> Cron.unsafeParse("1 1 1 31 * ?").next(oldDate)
res33: Option[org.joda.time.DateTime] = None

scala> Cron.unsafeParse("1 1 1 30 * ?").next(oldDate)
res34: Option[org.joda.time.DateTime] = Some(2016-09-30T01:01:01.000Z)
```

Should be  `Some(2016-10-31T01:01:01.000Z)`

**Comment by graingert** [comment]
It seems totally bizarre because I can match a time in the future from "2016-09-04T00:00:00.000Z"

```scala
scala> val newDate = new DateTime("2016-10-31T01:01:01.000Z", DateTimeZone.UTC)
newDate: org.joda.time.DateTime = 2016-10-31T01:01:01.000Z

scala> Cron.unsafeParse("1 1 1 31 * ?").allOf(newDate)
res44: Boolean = true
```

**Comment by graingert** [comment]
This also happens for "1 1 1 30 * ?" with an input date in February.

```scala
scala> val oldDate = new DateTime("2016-02-04T00:00:00.000Z", DateTimeZone.UTC)
oldDate: org.joda.time.DateTime = 2016-02-04T00:00:00.000Z

scala> Cron.unsafeParse("1 1 1 30 * ?").next(oldDate)
res46: Option[org.joda.time.DateTime] = None
```

It seems that cron is forgetting to roll on the month in this case.

**Comment by alonsodomin** [comment]
I see, surely what's happening here is that each field is getting rolled up individually from each other and when the turn comes for the _day of month_, it fails because the month of the original date is wrong as it hasn't been rolled up yet.

The reason why it works when matching is because the match operations do not perform any date field rolling, therefore, if you are able to have a `DateTime` object, the cron expression will always be able to tell you if it matches or not.

This is not too difficult to solve so I'll try to get something working ASAP. Thanks for reporting!

**Comment by graingert** [comment]
@alonsodomin any update on this?

**Comment by groblochon** [comment]
Hi !
```
val cronExp = "0 0 2 ? * *"
val Right(cron) = Cron(cronExp)
val previous = cron.prev(LocalTime.now())
```
In this case, previous is `None`.

**Comment by alonsodomin** [comment]
A fix has been merged into master, a new release will be published in the next days.

**Comment by graingert** [comment]
Thanks, that's super handy!
